#app
server:
    port: 8080

#spring
spring:
  devtools:
    restart:
      enabled: false
#springmvc
  mvc:
    view:
     prefix: /WEB-INF/jsp/
     suffix: .jsp
##profiles
  profiles:
     active: dev
##file
  http:
    multipart:  
      enabled: true  
      maxFileSize: 50mb  
      maxRequestSize: 100mb
      fileSizeThreshold: 0  
       
  # H2 DATABASE CONFIG
  datasource:
    schema: classpath:/db/schema-h2.sql
    data: classpath:/db/data-h2.sql
    url: jdbc:h2:mem:image
    username: sa
    password: sa
    initialize: true
    continue-on-error: true
  h2:
    console:
      enabled: true
      path: /console
      
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: fileupload.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #dbType
    dbType: h2
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#logging
logging:
  level: debug
